 /*
 * Copyright (C) 1994-2022 OpenTV, Inc. and Nagravision S.A.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#ifndef OSK_LAYOUT_H
#define OSK_LAYOUT_H

#include "OnScreenKeyBoard.h"
#include "RNSKeyCodeMapping.h"

/* KeyBoard Layout for Alpha Numeric KeyBoard */
#define ALPHA_NUMERIC_KEY_COUNT 54
keyPosition  alphaNumericKBPos[ALPHA_NUMERIC_KEY_COUNT]={{{-1,-1},},};
KeyLayoutInfo alphaNumericKBLayout[ALPHA_NUMERIC_KEY_COUNT] = {
    //row 1
    {"123ABC",static_cast<keyTypes>(GROUP_KEYS|ALPHA_UPPERCASE_KEYS),{ 0,KEY_VERTICAL_GAP+10},{0,1},RNS_KEY_UnKnown,13,1,28,14},
    {"1",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP+74,KEY_VERTICAL_GAP},{1,1},RNS_KEY_1,0,2,42,15 },
    {"2",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{2,1},RNS_KEY_2,1,3,43,16},
    {"3",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{3,1},RNS_KEY_3,2,4,44,17},
    {"a",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{4,1},RNS_KEY_a,3,5,45,18,"A"},
    {"b",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{5,1},RNS_KEY_b,4,6,46,19,"B"},
    {"c",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{6,1},RNS_KEY_c,5,7,47,20,"C"},
    {"d",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{7,1},RNS_KEY_d,6,8,48,21,"D"},
    {"e",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{8,1},RNS_KEY_e,7,9,49,22,"E"},
    {"f",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{9,1},RNS_KEY_f,8,10,50,23,"F"},
    {"g",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{10,1},RNS_KEY_g ,9,11,51,24,"G"},
    {"h" ,ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{11,1},RNS_KEY_h,10,12,52,25,"H"},
    {"i",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP},{12,1},RNS_KEY_i,11,13,53,26,"I"},
    {"space",ACTION_KEYS,{KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP+8},{13,1},RNS_KEY_Space ,12,0,42, 27,NULL,0x23B5},
     //row 2
    {"123abc",static_cast<keyTypes>(GROUP_KEYS|ALPHA_LOWERCASE_KEYS),{ 0,(KEY_VERTICAL_GAP)+10 },{0,2},RNS_KEY_UnKnown,27,15,0,28},
    {"4",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP+74,KEY_VERTICAL_GAP },{1,2},RNS_KEY_4,14,16,1,29},
    {"5",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{2,2},RNS_KEY_5,15,17,2,30},
    {"6",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{3,2},RNS_KEY_6,16,18,3,31},
    {"j",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{4,2},RNS_KEY_j,17,19,4,32,"J"},
    {"k",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{5,2},RNS_KEY_k,18,20,5,33,"K"},
    {"l",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{6,2},RNS_KEY_l,19,21,6,34,"L"},
    {"m",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{7,2},RNS_KEY_m ,20,22,7,35,"M"},
    {"n",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{8,2},RNS_KEY_n,21,23,8,36,"N"},
    {"o",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{9,2},RNS_KEY_o,22,24,9,37,"O"},
    {"p",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{10,2},RNS_KEY_p,23,25,10,38,"P"},
    {"q",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{11,2},RNS_KEY_q,24,26,11,39,"Q"},
    {"r",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{12,2},RNS_KEY_r,25,27,12,40,"R"},
    {"delete",ACTION_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP+8 },{13,2},RNS_KEY_Delete ,26,14,13,41,NULL,0x232B},
    //row 3
    {"@?#",static_cast<keyTypes>(GROUP_KEYS|SYMBOL_KEYS),{ 8,(KEY_VERTICAL_GAP)+10 },{0,3},RNS_KEY_UnKnown ,41,29,14,0},
    {"7",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP+66,KEY_VERTICAL_GAP },{1,3},RNS_KEY_7,28,30,15,42},
    {"8",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{2,3},RNS_KEY_8,29,31,16,43},
    {"9",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{3,3},RNS_KEY_9,30,32,17,44},
    {"s",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{4,3},RNS_KEY_s,31,33,18,45,"S"},
    {"t",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{5,3},RNS_KEY_t,32,34,19,46,"T"},
    {"u",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{6,3},RNS_KEY_u,33,35,20,47,"U"},
    {"v",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{7,3},RNS_KEY_v,34,36,21,48,"V"},
    {"w",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{8,3},RNS_KEY_w,35,37,22,49,"W"},
    {"x",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{9,3},RNS_KEY_x,36,38,23,50,"X"},
    {"y",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{10,3},RNS_KEY_y,37,39,24,51,"Y"},
    {"z",ALPHA_LOWERCASE_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{11,3},RNS_KEY_z,38,40,25,52,"Z"},
    {".",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{12,3},RNS_KEY_Period,39,41,26,53},
    {"done",ACTION_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP+8 },{13,3},RNS_KEY_Select,40,28,27,13,NULL,0x23CE},
      //row 4
    {"-",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP+64,KEY_VERTICAL_GAP },{0,4},RNS_KEY_Bar,53,43,29,1},
    {"0",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{1,4},RNS_KEY_0,42,44,30,2},
    {"_",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{2,4},RNS_KEY_Underscore,43,45,31,3 },
    {"!",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{3,4},RNS_KEY_Exclam,44,46,32,4},
    {"@",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{4,4},RNS_KEY_At,45,47,33,5 },
    {"#",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{5,4},RNS_KEY_Shash,46,48,34,6},
    {"?",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{6,4},RNS_KEY_Question,47,49,35,7},
    {"*",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{7,4},RNS_KEY_Asterisk,48,50,36,8},
    {",",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{8,4},RNS_KEY_Comma,49,51,37,9},
    {";",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{9,4},RNS_KEY_Semicolon,50,52,38,10},
    {"right",ACTION_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{10,4},RNS_KEY_Right ,51,53,39,11,NULL,0x25BA},
    {"left",ACTION_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{11,4},RNS_KEY_Left ,52,42,40,12,NULL,0x25c4}
};

/* KeyBoard Layout for Symbol Key Board */
#define SYMBOL_KEY_COUNT 38
keyPosition  symbolKBPos[SYMBOL_KEY_COUNT]={{{-1,-1},},};
KeyLayoutInfo symbolKBLayout[SYMBOL_KEY_COUNT]={
    {"123ABC",static_cast<keyTypes>(GROUP_KEYS|ALPHA_UPPERCASE_KEYS),{0,KEY_VERTICAL_GAP+8},{0,1},RNS_KEY_UnKnown,9,1,19,10},
    {"!",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP+74,KEY_VERTICAL_GAP },{1,1},RNS_KEY_Exclam,0,2,30,11},
    {"@",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{2,1},RNS_KEY_At,1,3,31,12},
    {"#",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{3,1},RNS_KEY_Shash,2,4,32,13},
    {"$",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{4,1},RNS_KEY_Dollar,3,5,33,14 },
    {"%",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{5,1},RNS_KEY_Percent,4,6,34,15},
    {"^",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{6,1},RNS_KEY_Apostrophe,5,7,35,16},
    {"&",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP} ,{7,1},RNS_KEY_Ampersand,6,8,36,17},
    {"*",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{8,1},RNS_KEY_Asterisk,7,9,37,18},
    {"backspace",ACTION_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{9,1},RNS_KEY_Space ,8,0,29,19},
     //row 2
    {"123abc",static_cast<keyTypes>(GROUP_KEYS|ALPHA_LOWERCASE_KEYS),{ 0,(KEY_VERTICAL_GAP)+8},{0,2},RNS_KEY_UnKnown,19,11,0,20},
    {"(",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP+74,KEY_VERTICAL_GAP },{1,2},RNS_KEY_BraceLeft,10,12,1,21},
    {")",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{2,2},RNS_KEY_BraceRight,11,13,2,22},
    {",",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{3,2},RNS_KEY_Comma,12,14,3,23},
    {".",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{4,2},RNS_KEY_Period,13,15,4,24},
    {"?",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{5,2},RNS_KEY_Question,14,16,5,25},
    {",",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{6,2},RNS_KEY_Comma,15,17,6,26},
    {";",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{7,2},RNS_KEY_Semicolon ,16,18,7,27},
    {":",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{8,2},RNS_KEY_Colon,17,19,8,28},
    {"delete",ACTION_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{9,2},RNS_KEY_Delete,18,10,9,29},
    //row 3
    {"@?#",static_cast<keyTypes>(GROUP_KEYS|SYMBOL_KEYS),{ 0,(KEY_VERTICAL_GAP)+8 },{0,3},RNS_KEY_UnKnown ,29,21,10,0},
    {"|",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP+74,KEY_VERTICAL_GAP },{1,3},RNS_KEY_7,20,22,11,31},
    {"\\",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{2,3},RNS_KEY_8,21,23,12,32 },
    {"/",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{3,3},RNS_KEY_9,22,24,13,33},
    {"{",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{4,3},RNS_KEY_s,23,25,14,34},
    {"}",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{5,3},RNS_KEY_t,24,26,15,35},
    {"[",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{6,3},RNS_KEY_ParenLeft,25,27,16,36},
    {"]",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{7,3},RNS_KEY_ParenRight,26,28,17,37},
    {"~",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{8,3},RNS_KEY_w,27,29,18,38},
    {"done",ACTION_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{9,3},RNS_KEY_Select,28,20,19,9},
      //row 4
    {"`",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP+74,KEY_VERTICAL_GAP },{0,4},RNS_KEY_1,37,31,21,1},
    {"=",NUMERIC_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{1,4},RNS_KEY_Equal,30,32,22,2},
    {"+",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{2,4},RNS_KEY_Plus,31,33,23,3},
    {"-",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{3,4},RNS_KEY_Minus,32,34,24,4},
    {"_",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{4,4},RNS_KEY_Underscore,33,35,25,5},
    {"%",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{5,4},RNS_KEY_Minus,34,36,26,6},
    {">",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{6,4},RNS_KEY_Greater,35,37,27,7},
    {"<",SYMBOL_KEYS,{ KEY_HORIZONTAL_GAP,KEY_VERTICAL_GAP },{7,4},RNS_KEY_Lesser,36,30,28,8}
};

/* KeyBoard Layout for Numeric Key Board */
#define  NUMERIC_KEY_COUNT 16
keyPosition  numericKBPos[NUMERIC_KEY_COUNT]={{{-1,-1},},};
KeyLayoutInfo numericKBLayout[NUMERIC_KEY_COUNT]={
    {"1",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP},{1,1},RNS_KEY_1,3,1,12,4},
    {"2",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP},{2,1},RNS_KEY_2,0,2,13,5},
    {"3",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP},{3,1},RNS_KEY_3,1,3,14,6},
    {"-",SYMBOL_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP},{4,1},RNS_KEY_Underscore,2,0,15,7},
     //row 2
    {"4",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*2},{1,2},RNS_KEY_4,7,5,0,8},
    {"5",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*2},{2,2},RNS_KEY_5,4,6,1,9},
    {"6",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*2},{3,2},RNS_KEY_6,5,7,2,10},
    {"backspace",ACTION_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*2},{4,2},RNS_KEY_Space,6,4,3,11},
    //row 3
    {"7",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*3},{1,3},RNS_KEY_7,11,9,8,12},
    {"8",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*3},{2,3},RNS_KEY_8,8,10,9,13},
    {"9",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*3},{3,3},RNS_KEY_9,9,11,10,14},
    {"delete",ACTION_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*3},{4,2},RNS_KEY_Delete,10,8,11,15},
      //row 4
    {",",SYMBOL_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*4},{0,4},RNS_KEY_Comma,15,13,12,0},
    {"0",NUMERIC_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*4},{1,4},RNS_KEY_0,12,14,13,1},
    {".",SYMBOL_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*4},{2,4},RNS_KEY_Underscore,13,15,14,2 },
    {"done",ACTION_KEYS,{NUM_KB_HORIZONTAL_GAP,NUM_KB_VERTICAL_GAP*4},{3,4},RNS_KEY_Select,14,12,15,3}
};
#endif// OSK_LAYOUT_H
